import { LanguagesRecord } from './languages';

/**
 * Un mapa que categoriza lenguajes de programación, tecnologías y formatos
 * según su propósito principal dentro del desarrollo de software.
 *
 * Las claves representan nombres de lenguajes o tecnologías, y los valores
 * indican su categoría funcional, como por ejemplo:
 * - `'frontend'`: tecnologías orientadas a la interfaz de usuario.
 * - `'backend'`: lenguajes usados en lógica de servidor o procesamiento.
 * - `'scripting'`: lenguajes usados para automatización o scripts.
 * - `'build'`: herramientas de construcción y configuración.
 * - `'template'`: motores de plantillas para generar contenido dinámico.
 * - `'data'`: formatos o lenguajes centrados en el manejo de datos.
 * - `'documentation'`: lenguajes usados para escribir documentación técnica.
 * - `'academic'`: lenguajes usados en investigación o enseñanza.
 * - `'embedded'`: lenguajes para sistemas embebidos o hardware.
 * - `'graphics'`: tecnologías para renderizado o procesamiento visual.
 * - `'tooling'`: lenguajes o archivos usados por herramientas de desarrollo.
 * - `'testing'`: tecnologías para pruebas automatizadas.
 * - `'game'`: lenguajes usados en desarrollo de videojuegos.
 * - `'network'`: tecnologías relacionadas con redes.
 * - `'devops'`: herramientas para infraestructura y operaciones.
 * - `'blockchain'`: lenguajes usados en desarrollo de contratos inteligentes.
 *
 * Este objeto es útil para:
 * - Clasificar lenguajes en visualizaciones o filtros.
 * - Generar agrupaciones por tipo en interfaces de usuario.
 * - Analizar el uso de tecnologías por dominio.
 *
 * @example
 * ```ts
 * const category = languagesCategory['Python']; // 'scripting'
 * ```
 *
 * @remarks
 * Este objeto implementa la interfaz `LanguagesRecord`, donde cada clave es
 * un nombre de lenguaje y el valor es una cadena que representa su categoría.
 */
export const languagesCategory: LanguagesRecord = {
  ABAP: 'backend',
  ActionScript: 'frontend',
  Ada: 'backend',
  'ADSO/IDSM': 'backend',
  Agda: 'academic',
  AMPLE: 'backend',
  AnsProlog: 'academic',
  Ant: 'build',
  'ANTLR Grammar': 'tooling',
  'Apex Class': 'backend',
  'Apex Trigger': 'backend',
  APL: 'academic',
  AppleScript: 'scripting',
  'Arduino Sketch': 'embedded',
  ArkTs: 'frontend',
  Arturo: 'scripting',
  AsciiDoc: 'documentation',
  ASP: 'backend',
  'ASP.NET': 'backend',
  AspectJ: 'backend',
  Assembly: 'embedded',
  Astro: 'frontend',
  Asymptote: 'academic',
  AutoHotkey: 'scripting',
  awk: 'scripting',
  Bazel: 'build',
  BitBake: 'build',
  'BizTalk Orchestration': 'backend',
  'BizTalk Pipeline': 'backend',
  Blade: 'frontend',
  'Bourne Again Shell': 'scripting',
  'Bourne Shell': 'scripting',
  BrightScript: 'embedded',
  builder: 'build',
  C: 'backend',
  'C Shell': 'scripting',
  'C#': 'backend',
  'C# Designer': 'tooling',
  'C++': 'backend',
  'C/C++ Header': 'backend',
  Cairo: 'graphics',
  'Cake Build Script': 'build',
  Carbon: 'backend',
  CCS: 'embedded',
  Chapel: 'academic',
  Circom: 'blockchain',
  Clean: 'academic',
  Clojure: 'backend',
  ClojureC: 'backend',
  ClojureScript: 'frontend',
  CMake: 'build',
  COBOL: 'backend',
  'CoCoA 5': 'academic',
  CoffeeScript: 'frontend',
  ColdFusion: 'backend',
  'ColdFusion CFScript': 'backend',
  'Constraint Grammar': 'academic',
  Containerfile: 'devops',
  Coq: 'academic',
  Crystal: 'backend',
  CSON: 'data',
  CSS: 'frontend',
  CSV: 'data',
  Cucumber: 'testing',
  CUDA: 'backend',
  Cython: 'backend',
  D: 'backend',
  Dafny: 'academic',
  DAL: 'backend',
  Dart: 'frontend',
  'Delphi Form': 'tooling',
  DenizenScript: 'scripting',
  Derw: 'frontend',
  dhall: 'data',
  DIET: 'template',
  diff: 'tooling',
  DITA: 'documentation',
  Dockerfile: 'devops',
  'DOORS Extension Language': 'tooling',
  'DOS Batch': 'scripting',
  Drools: 'backend',
  DTD: 'data',
  dtrace: 'tooling',
  ECPP: 'template',
  EEx: 'template',
  EJS: 'template',
  Elixir: 'backend',
  Elm: 'frontend',
  'Embedded Crystal': 'template',
  ERB: 'template',
  Erlang: 'backend',
  Expect: 'testing',
  'F#': 'backend',
  'F# Script': 'scripting',
  Fennel: 'scripting',
  'Finite State Language': 'academic',
  'Fish Shell': 'scripting',
  Flatbuffers: 'data',
  Focus: 'backend',
  Forth: 'embedded',
  'Fortran 77': 'backend',
  'Fortran 90': 'backend',
  'Fortran 95': 'backend',
  'Freemarker Template': 'template',
  Futhark: 'academic',
  FXML: 'frontend',
  GDScript: 'game',
  'Gencat NLS': 'data',
  Glade: 'frontend',
  Gleam: 'backend',
  'Glimmer JavaScript': 'frontend',
  'Glimmer TypeScript': 'frontend',
  GLSL: 'graphics',
  Go: 'backend',
  'Godot Resource': 'game',
  'Godot Scene': 'game',
  'Godot Shaders': 'game',
  Gradle: 'build',
  Grails: 'backend',
  GraphQL: 'data',
  Groovy: 'backend',
  Haml: 'template',
  Handlebars: 'template',
  Harbour: 'backend',
  Hare: 'backend',
  Haskell: 'academic',
  Haxe: 'frontend',
  HCL: 'devops',
  HLSL: 'graphics',
  HolyC: 'academic',
  Hoon: 'academic',
  HTML: 'frontend',
  'HTML EEx': 'template',
  IDL: 'data',
  Idris: 'academic',
  'Igor Pro': 'academic',
  Imba: 'frontend',
  INI: 'data',
  InstallShield: 'build',
  IPL: 'academic',
  Jai: 'backend',
  Janet: 'scripting',
  Java: 'backend',
  JavaScript: 'frontend',
  'JavaServer Faces': 'frontend',
  JCL: 'backend',
  'Jinja Template': 'template',
  JSON: 'data',
  JSON5: 'data',
  JSP: 'template',
  JSX: 'frontend',
  Julia: 'academic',
  'Juniper Junos': 'network',
  'Jupyter Notebook': 'data',
  Kermit: 'network',
  'Korn Shell': 'scripting',
  Kotlin: 'backend',
  kvlang: 'frontend',
  Lean: 'academic',
  Lem: 'academic',
  LESS: 'frontend',
  lex: 'tooling',
  LFE: 'backend',
  'Linker Script': 'tooling',
  liquid: 'template',
  Lisp: 'academic',
  'Literate Idris': 'academic',
  'LiveLink OScript': 'scripting',
  'LLVM IR': 'tooling',
  Logos: 'backend',
  Logtalk: 'academic',
  Lua: 'scripting',
  Luau: 'game',
  m4: 'build',
  make: 'build',
  Mako: 'template',
  Markdown: 'documentation',
  Mathematica: 'academic',
  MATLAB: 'academic',
  Maven: 'build',
  Meson: 'build',
  Metal: 'graphics',
  Modelica: 'academic',
  Modula3: 'academic',
  Mojo: 'backend',
  Mojom: 'backend',
  MoonBit: 'backend',
  'MSBuild script': 'build',
  MUMPS: 'backend',
  Mustache: 'template',
  MXML: 'frontend',
  'NAnt script': 'build',
  'NASTRAN DMAP': 'academic',
  Nemerle: 'academic',
  NetLogo: 'academic',
  Nickel: 'academic',
  Nim: 'backend',
  Nix: 'devops',
  Nunjucks: 'template',
  'Objective-C': 'backend',
  'Objective-C++': 'backend',
  OCaml: 'academic',
  Odin: 'backend',
  OpenCL: 'graphics',
  OpenSCAD: 'graphics',
  'Oracle Forms': 'backend',
  'Oracle PL/SQL': 'backend',
  'Oracle Reports': 'backend',
  P4: 'network',
  Pascal: 'backend',
  'Pascal/Pawn': 'game',
  'Pascal/Puppet': 'devops',
  'Patran Command Language': 'academic',
  Pawn: 'game',
  PEG: 'tooling',
  'peg.js': 'tooling',
  peggy: 'tooling',
  Perl: 'scripting',
  Pest: 'tooling',
  PHP: 'backend',
  'PHP/Pascal/Fortran/Pawn/Bitbake': 'build',
  'Pig Latin': 'data',
  'PL/I': 'backend',
  'PL/M': 'backend',
  PlantUML: 'documentation',
  'PO File': 'data',
  Pony: 'backend',
  PowerBuilder: 'backend',
  PowerShell: 'scripting',
  'Prisma Schema': 'data',
  Processing: 'graphics',
  ProGuard: 'tooling',
  Prolog: 'academic',
  Properties: 'data',
  'Protocol Buffers': 'data',
  PRQL: 'data',
  Pug: 'template',
  PureScript: 'frontend',
  Python: 'scripting',
  QML: 'frontend',
  Qt: 'frontend',
  'Qt Linguist': 'tooling',
  'Qt Project': 'tooling',
  R: 'data',
  Racket: 'academic',
  Raku: 'scripting',
  'Raku/Prolog': 'academic',
  RAML: 'data',
  RapydScript: 'frontend',
  Razor: 'template',
  ReasonML: 'frontend',
  Rego: 'devops',
  ReScript: 'frontend',
  reStructuredText: 'documentation',
  Rexx: 'scripting',
  Ring: 'backend',
  Rmd: 'documentation',
  RobotFramework: 'testing',
  Ruby: 'backend',
  'Ruby HTML': 'template',
  Rust: 'backend',
  SaltStack: 'devops',
  SAS: 'data',
  Sass: 'frontend',
  Scala: 'backend',
  Scheme: 'academic',
  SCSS: 'frontend',
  sed: 'scripting',
  SKILL: 'embedded',
  'SKILL++': 'embedded',
  Slice: 'data',
  Slim: 'template',
  Slint: 'frontend',
  Smalltalk: 'academic',
  Smarty: 'template',
  Snakemake: 'data',
  'Softbridge Basic': 'backend',
  Solidity: 'blockchain',
  SparForte: 'academic',
  'Specman e': 'embedded',
  SQL: 'data',
  'SQL Data': 'data',
  'SQL Stored Procedure': 'data',
  Squirrel: 'game',
  'Standard ML': 'academic',
  Starlark: 'build',
  Stata: 'data',
  Stylus: 'frontend',
  SugarSS: 'frontend',
  Svelte: 'frontend',
  SVG: 'graphics',
  Swift: 'frontend',
  SWIG: 'tooling',
  TableGen: 'tooling',
  'Tcl/Tk': 'scripting',
  TEAL: 'scripting',
  'Teamcenter met': 'tooling',
  'Teamcenter mth': 'tooling',
  Templ: 'template',
  TeX: 'documentation',
  Text: 'data',
  'Unknown/BitBake': 'build',
  Thrift: 'data',
  'TITAN Project File Information': 'tooling',
  'Titanium Style Sheet': 'frontend',
  'TLA+': 'academic',
  TNSDL: 'embedded',
  TOML: 'data',
  tspeg: 'tooling',
  TTCN: 'testing',
  Twig: 'template',
  TypeScript: 'frontend',
  Typst: 'documentation',
  Umka: 'backend',
  'Unity-Prefab': 'game',
  USS: 'tooling',
  UXML: 'frontend',
  Vala: 'backend',
  'Vala Header': 'backend',
  'VB for Applications': 'backend',
  'Velocity Template Language': 'template',
  'Verilog-SystemVerilog': 'embedded',
  VHDL: 'embedded',
  'vim script': 'scripting',
  'Visual Basic': 'backend',
  'Visual Basic .NET': 'backend',
  'Visual Basic Script': 'scripting',
  'Visual Fox Pro': 'backend',
  'Visual Studio Solution': 'tooling',
  'Visualforce Component': 'frontend',
  'Visualforce Page': 'frontend',
  'Vuejs Component': 'frontend',
  Vyper: 'blockchain',
  'Web Services Description': 'data',
  WebAssembly: 'backend',
  WGSL: 'graphics',
  'Windows Message File': 'data',
  'Windows Module Definition': 'tooling',
  'Windows Resource File': 'tooling',
  'WiX include': 'tooling',
  'WiX source': 'tooling',
  'WiX string localization': 'tooling',
  WXML: 'frontend',
  xBase: 'backend',
  XMI: 'data',
  XQuery: 'backend',
  XSD: 'data',
  XSLT: 'tooling',
  Xtend: 'backend',
  YAML: 'data',
  Zig: 'backend',
  zsh: 'scripting',
  WXSS: 'frontend',
  'X++': 'backend',
  XAML: 'frontend',
  XML: 'data',
  XHTML: 'frontend',
  'xBase Header': 'backend',
  yacc: 'tooling',
  Yang: 'data',
};
